# Monta solo el API y reutiliza el contenedor de bases de datos
services:
  apaw-practice:
    build: .
    image: apaw-practice:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@host.docker.internal:27017/apawdb?authSource=admin
    networks:
      - apawnet

networks:
  apawnet:
    external: true

#> docker compose up --build -d

