# Monta solo el API y reutiliza el contenedor de bases de datos
services:
  apaw-practice:
    build: .
    image: apaw-practice:latest
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apawpracticedb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://apaw-eureka:8761/eureka/
    networks:
      - apawnet

networks:
  apawnet:
    external: true

#> docker network create apawnet
#> docker compose up --build -d

# CONSOLA & COMANDOS Postgres
#> docker exec -it postgres  psql -U postgres
#> create database apawpracticedb;
