spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/dbapawpractice
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://apaw-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  hosting: AWS
