server:
  port: 8082

info:
  app:
    artifact: "@project.artifactId@"
    version: "@project.version@"
    build: "@maven.build.timestamp@"

spring:
  application:
    name: apaw-practice
  profiles:
    default: dev
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false

app:
  hosting: localhost

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    es.upm: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/