name: CD. AWS Lightsail
on:
  push:
    branches:
      - staging

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🏷️ Prepare container registry metadata (repository, artifact, version...)
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV          
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest

      - name: 🚀 Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_STAGING }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_STAGING }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_STAGING }}
          script: |
            echo ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ env.REPOSITORY }}:latest
            docker rm -f ${{ env.ARTIFACT }} || true
            docker run -d \
              --name ${{ env.ARTIFACT }} \
              --restart always \
              --memory 512m \
              --network apawnet \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e POSTGRES_URL=${{ secrets.POSTGRES_URL_STAGING }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER_STAGING }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_STAGING }} \
              ghcr.io/${{ env.REPOSITORY }}:latest

            echo "⏳ Esperando a que se levante"
            for i in $(seq 1 12); do
              sleep 15
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' ${{ env.ARTIFACT }} 2>/dev/null || echo "no-existe")
              echo "Intento $i: $STATUS"
              [ "$STATUS" = "healthy" ] && break
            done

            if [ "$STATUS" != "healthy" ]; then
              echo "❌ Deploy fallido"
              docker logs --tail 50 ${{ env.ARTIFACT }}
              exit 1
            fi

            echo "✅ Deploy exitoso"
            docker image prune --filter "until=12h" -f
